// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIlttuj15R5XdmXO7_rxbQ2OJJv9CfuM',
    appId: '1:1057578835114:android:aa4d82ae085aab922c04d3',
    messagingSenderId: '1057578835114',
    projectId: 'demoproject-9fc4d',
    databaseURL: 'https://demoproject-9fc4d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiaxuV_j2SfWaqEr0VPsS8kQ_dbYLR6I',
    appId: '1:1057578835114:ios:62113c6acceda57e2c04d3',
    messagingSenderId: '1057578835114',
    projectId: 'demoproject-9fc4d',
    databaseURL: 'https://demoproject-9fc4d-default-rtdb.firebaseio.com',
    storageBucket: 'demoproject-9fc4d.appspot.com',
    androidClientId: '1057578835114-033vb140s5cvoi5mel94ku6o9llpvb4g.apps.googleusercontent.com',
    iosBundleId: 'com.manal.secondHome',
  );
}
